# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: mvn clean install -DskipTests=true
      
  Health-Checked:
    runs-on: ubuntu-latest
    environment: dev-test
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Health-Checked
      run: mvn test -DTests=healthcheck
